// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5pjQtrl-vP5Ifiha3oqbSAjhHTGRBNo',
    appId: '1:1098589060105:web:6c0daa089da73afdd30cd8',
    messagingSenderId: '1098589060105',
    projectId: 'profilehub-81669',
    authDomain: 'profilehub-81669.firebaseapp.com',
    storageBucket: 'profilehub-81669.firebasestorage.app',
    measurementId: 'G-RM6Z6WN1KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyDTb_4lPFOqIr4MwbBMjczz43uyTY2Hw',
    appId: '1:1098589060105:android:4b2261b82ed312ffd30cd8',
    messagingSenderId: '1098589060105',
    projectId: 'profilehub-81669',
    storageBucket: 'profilehub-81669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrEdZYG0-5vAPuyH5dvjbhibOyVsBWDPE',
    appId: '1:1098589060105:ios:6e786400c050341dd30cd8',
    messagingSenderId: '1098589060105',
    projectId: 'profilehub-81669',
    storageBucket: 'profilehub-81669.firebasestorage.app',
    iosBundleId: 'com.example.profilehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrEdZYG0-5vAPuyH5dvjbhibOyVsBWDPE',
    appId: '1:1098589060105:ios:6e786400c050341dd30cd8',
    messagingSenderId: '1098589060105',
    projectId: 'profilehub-81669',
    storageBucket: 'profilehub-81669.firebasestorage.app',
    iosBundleId: 'com.example.profilehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP5pjQtrl-vP5Ifiha3oqbSAjhHTGRBNo',
    appId: '1:1098589060105:web:f7fdb68cafc0971cd30cd8',
    messagingSenderId: '1098589060105',
    projectId: 'profilehub-81669',
    authDomain: 'profilehub-81669.firebaseapp.com',
    storageBucket: 'profilehub-81669.firebasestorage.app',
    measurementId: 'G-MZMQZQBXWV',
  );
}
